### ISSUE TITLE
MT-H2M88H Support

### ISSUE THREAD

**Issue by ukiews** [bitfocus/companion-module-mt-viki-matrix#5]
Would this work with this model?
https://a.co/d/5Y4HRAx

**Comment by JeLuF** [comment]
~~I'm not sure what this device is supposed to be. The listing says both "Video Wall Controller 4x2 Seamless" (not supported) and "8x8 HDMI Matrix Switcher" (This is the device I tested the module with). These are two different MT-Viki products and I can't tell you which one you'd get. The pictures show the 8x8 matrix.~~

**Comment by JeLuF** [comment]
PS: I just double checked. This seems to be a different device to [the one I use](https://www.amazon.de/gp/product/B0C7CCPDR5/). Notice the 3.5mm audio connectors on your device which are not on mine.

User manual:
https://www.mt-viki.net/wp-content/uploads/2024/08/HDMI-2.0-Seamless-Splicing-Matrix-users-manual-20240320.pdf

According to the manual, this switcher uses a different protocol. Command to map input 1 to output 2: My device: `SW 1 2`, this device: `1X2.`

So no, this device can't be controlled via this module.
